spring:
  # 실제 데이터베이스 접속 정보
  datasource:
    url: jdbc:postgresql://database-1.ctgq4si8sh83.ap-northeast-2.rds.amazonaws.com:5432/board
    driverClassName: org.postgresql.Driver
    username: postgres
    password: tf9CL9ptvaS67kq1MPhR

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect